import JSZip from 'jszip';
import mammoth from 'mammoth';
import { Question } from '../types';
import { compressBase64DataUrl } from './imageCompressor';
import { injectLatexIntoWordDocumentXml } from './ommlToLatex';

export interface WordImportResult {
  questions: Question[];
  totalParsed: number;
  mcCount: number; // Single choice count
  mrCount: number; // Multiple response count
  imageCount: number; // Questions with embedded images
  mathFormulaCount: number; // Questions containing mathematical formulas/fractions
  recoveredQuestionCount: number; // Questions auto-healed/separated from swallowed blocks
  detectedSequence: string; // e.g. "1 - 20 (Lengkap)"
  warnings: string[];
}

/**
 * Helper to convert letter ('A' | 'B' | 'C' | 'D' | 'E') to 0-based index.
 */
function letterToIndex(letter: string): number {
  const code = letter.toUpperCase().charCodeAt(0);
  return Math.max(0, code - 65); // 'A' -> 0, 'B' -> 1, 'C' -> 2, 'D' -> 3, 'E' -> 4
}

/**
 * Clean non-breaking spaces and normalize invisible Word characters.
 */
function normalizeWordText(text: string): string {
  if (!text) return '';
  return text
    .replace(/[\u00A0\u2007\u202F]/g, ' ') // Non-breaking spaces
    .replace(/[\u200B-\u200D\uFEFF]/g, '') // Zero-width spaces
    .replace(/\r\n/g, '\n')
    .replace(/\r/g, '\n')
    .replace(/[\t]+/g, ' ')
    .trim();
}

/**
 * Normalizes plain mathematical notations into KaTeX-compatible LaTeX:
 * - Superscripts: x², cm³, 10⁻⁵ -> $x^2$, cm$^3$, $10^{-5}$
 * - Subscripts: H₂O -> $H_2O$
 * - Degree: 90° -> $90^\circ$
 * - Symbols: ±, ×, ÷, ≤, ≥, ≠, π, √
 */
export function enhanceMathText(rawText: string): { text: string; hasMath: boolean } {
  if (!rawText) return { text: '', hasMath: false };

  let text = rawText;
  let hasMath = false;

  // Check if text already has LaTeX ($...$ or $$...$$)
  if (text.includes('$') || text.includes('\\frac') || text.includes('\\sqrt')) {
    hasMath = true;
  }

  // Convert HTML <sup> and <sub> tags generated by Mammoth from Word into LaTeX
  if (text.includes('<sup>') || text.includes('<sub>')) {
    hasMath = true;
    text = text.replace(/<sup>(.*?)<\/sup>/gi, (_, sup) => `^{${sup}}`);
    text = text.replace(/<sub>(.*?)<\/sub>/gi, (_, sub) => `_{${sub}}`);
  }

  // Convert common Unicode superscripts
  const unicodeSupMap: Record<string, string> = {
    '⁰': '0', '¹': '1', '²': '2', '³': '3', '⁴': '4',
    '⁵': '5', '⁶': '6', '⁷': '7', '⁸': '8', '⁹': '9',
    '⁺': '+', '⁻': '-', 'ⁿ': 'n', 'ˣ': 'x'
  };
  const supRegex = /([a-zA-Z0-9\)])([⁰¹²³⁴⁵⁶⁷⁸⁹⁺⁻ⁿˣ]+)/g;
  if (supRegex.test(text)) {
    hasMath = true;
    text = text.replace(supRegex, (_, base, sups) => {
      const converted = sups.split('').map((c: string) => unicodeSupMap[c] || c).join('');
      return `${base}^{${converted}}`;
    });
  }

  // Convert common Unicode roots: √x or √(x) or √25
  const rootRegex = /√([a-zA-Z0-9]+|\([^\)]+\))/g;
  if (rootRegex.test(text)) {
    hasMath = true;
    text = text.replace(rootRegex, (_, content) => {
      const clean = content.startsWith('(') && content.endsWith(')') ? content.slice(1, -1) : content;
      return `$\\sqrt{${clean}}$`;
    });
  }

  // Convert standalone square root symbol √ without immediate arg
  if (text.includes('√')) {
    hasMath = true;
    text = text.replace(/√\s*([0-9a-zA-Z]+)/g, '$\\sqrt{$1}$');
  }

  // Convert degree symbol attached to numbers: e.g. 45° or 180°
  text = text.replace(/(\d+)\s*°/g, '$1^\\circ');

  // Convert isolated common math symbols if inside algebraic context
  if (text.includes('±') || text.includes('≠') || text.includes('≤') || text.includes('≥') || text.includes('≈')) {
    hasMath = true;
  }

  return { text, hasMath };
}

/**
 * Parse bottom "Kunci Jawaban" section into a mapping of question number -> correct letter array.
 */
function parseAnswerKeysSection(text: string, html: string): Map<number, string[]> {
  const keyMap = new Map<number, string[]>();

  // 1. Try DOM table extraction first (if answer keys are in a table)
  try {
    const parser = new DOMParser();
    const doc = parser.parseFromString(html, 'text/html');
    const tables = doc.querySelectorAll('table');
    for (const table of tables) {
      const rows = table.querySelectorAll('tr');
      for (const row of rows) {
        const cells = Array.from(row.querySelectorAll('td, th')).map(c => normalizeWordText(c.textContent || ''));
        if (cells.length >= 2) {
          const qNum = parseInt(cells[0].replace(/[^\d]/g, ''), 10);
          if (!isNaN(qNum) && qNum > 0) {
            const letters = cells[1].toUpperCase().match(/[A-E]/g);
            if (letters && letters.length > 0) {
              keyMap.set(qNum, Array.from(new Set(letters)));
            }
          }
        }
      }
    }
  } catch {
    // ignore
  }

  if (keyMap.size > 0) return keyMap;

  // 2. Parse plain text line by line or pattern matches
  // Matches patterns like: "1. A", "1) B, C", "1: A & D", "No. 1: B", "1 = A", "1.A 2.B 3.C"
  const itemRegex = /(?:(?:no\.?\s*)?(\d+)[\.\)\:\=\s\-]+([A-Ea-e\s\,\&\/\+dan]+))/gi;
  let match: RegExpExecArray | null;

  while ((match = itemRegex.exec(text)) !== null) {
    const qNum = parseInt(match[1], 10);
    const rawVal = match[2];
    if (!isNaN(qNum) && qNum > 0 && rawVal) {
      const letters = rawVal.toUpperCase().match(/[A-E]/g);
      if (letters && letters.length > 0) {
        keyMap.set(qNum, Array.from(new Set(letters)));
      }
    }
  }

  // 3. Fallback line by line
  if (keyMap.size === 0) {
    const lines = text.split('\n');
    for (const line of lines) {
      const trimmed = normalizeWordText(line);
      if (!trimmed) continue;
      const lineMatch = trimmed.match(/^(?:no\.?\s*)?(\d+)[\.\)\:\=\s\-]+(.*)$/i);
      if (lineMatch) {
        const qNum = parseInt(lineMatch[1], 10);
        const letters = lineMatch[2].toUpperCase().match(/[A-E]/g);
        if (!isNaN(qNum) && letters && letters.length > 0) {
          keyMap.set(qNum, Array.from(new Set(letters)));
        }
      }
    }
  }

  return keyMap;
}

/**
 * Split single text line containing multiple horizontal options into separate options.
 * e.g. "A. Merah   B. Kuning   C. Hijau   D. Biru"
 */
function splitHorizontalOptions(text: string): { letter: string; text: string; isCorrect: boolean }[] | null {
  const markerRegex = /(?:^|[\s\t]{2,}|\n)([\*]{1,2})?\s*\(?([A-Ea-e])\)?[.\-\s]\s*/g;
  const matches: { index: number; length: number; letter: string; asterisks: string }[] = [];
  let m: RegExpExecArray | null;

  while ((m = markerRegex.exec(text)) !== null) {
    matches.push({
      index: m.index,
      length: m[0].length,
      letter: m[2].toUpperCase(),
      asterisks: m[1] || ''
    });
  }

  if (matches.length >= 2) {
    const results: { letter: string; text: string; isCorrect: boolean }[] = [];
    for (let i = 0; i < matches.length; i++) {
      const start = matches[i].index + matches[i].length;
      const end = i + 1 < matches.length ? matches[i + 1].index : text.length;
      const optContent = text.substring(start, end).trim();
      results.push({
        letter: matches[i].letter,
        text: optContent,
        isCorrect: matches[i].asterisks.length > 0
      });
    }
    return results;
  }

  return null;
}

interface RawOption {
  letter: string;
  text: string;
  isCorrect: boolean;
  image?: string;
}

interface RawQuestionDraft {
  qNum: number;
  textParts: string[];
  images: string[];
  options: RawOption[];
}

/**
 * Checks if a string looks like a new question starting marker:
 * e.g. "1. ", "1) ", "Soal 1. ", "No. 1 ", "(1) "
 */
function matchQuestionStart(text: string): { qNum: number; remainingText: string } | null {
  const normalized = normalizeWordText(text);
  if (!normalized) return null;

  // Regex patterns:
  // 1. "1. Soal..." or "1) Soal..." or "1 - Soal..." or "1: Soal..."
  // 2. "Soal 1. ..." or "Soal No. 1: ..." or "No. 1. ..."
  // 3. "(1) Soal..." or "[1] Soal..."
  const patterns = [
    /^(?:soal\s+)?(?:no\.?\s*|nomor\s*)?(\d+)[\.\)\:\-\s]\s*(.*)$/i,
    /^\((\d+)\)[\.\s]\s*(.*)$/,
    /^\[(\d+)\][\.\s]\s*(.*)$/,
    /^(?:soal|nomor|no)\s+(\d+)\s*[\.\:\-]?\s*(.*)$/i,
  ];

  for (const re of patterns) {
    const m = normalized.match(re);
    if (m) {
      const num = parseInt(m[1], 10);
      if (!isNaN(num) && num > 0) {
        return { qNum: num, remainingText: m[2] ? m[2].trim() : '' };
      }
    }
  }

  return null;
}

/**
 * Checks if a string looks like an option starting marker:
 * e.g. "A. ", "B. ", "a) ", "*C. ", "**D. "
 */
function matchOptionStart(text: string): { letter: string; optText: string; isCorrect: boolean } | null {
  const normalized = normalizeWordText(text);
  if (!normalized) return null;

  // Match: "*A. Pilihan" or "A. Pilihan" or "A) Pilihan" or "(A) Pilihan" or "a. Pilihan"
  const m = normalized.match(/^(\*{1,2})?\s*\(?([A-Ea-e])\)?[.\-\s]\s*(.*)$/);
  if (m) {
    const asterisks = m[1] || '';
    const letter = m[2].toUpperCase();
    const optText = m[3] ? m[3].trim() : '';

    // Guard against common false positives like "A. Yani" or "B. J. Habibie"
    // An option start shouldn't look like initials followed by another initial (e.g. "A. Yani")
    if (optText.match(/^[A-Z]\.\s+[A-Za-z]+/)) {
      return null;
    }

    return {
      letter,
      optText,
      isCorrect: asterisks.length > 0
    };
  }

  return null;
}

/**
 * Checks if a numbered line is actually a sub-stimulus inside a question
 * e.g. "1) Memiliki 4 sisi" or "2) Memiliki sepasang sisi sejajar"
 * rather than a new question.
 */
function isSubStimulusItem(text: string, currentDraft: RawQuestionDraft | null): boolean {
  if (!currentDraft) return false;
  // If options have already started, it's not a stimulus statement
  if (currentDraft.options.length > 0) return false;

  const normalized = normalizeWordText(text);
  // Match patterns like "1)", "(1)", "1.", "i)", "ii)"
  const m = normalized.match(/^(?:(?:\(|\b)([1-9]|i{1,3}|iv|v)\)[\.\s]*)(.*)$/i);
  if (!m) return false;

  const subIndex = parseInt(m[1], 10);
  // If subIndex is 1, 2, 3, 4, 5 and current question number is >= 2, or if current question text already exists
  if (currentDraft.textParts.length > 0) {
    const fullText = currentDraft.textParts.join(' ').toLowerCase();
    if (
      fullText.includes('perhatikan') ||
      fullText.includes('berikut') ||
      fullText.includes('pernyataan') ||
      fullText.includes('tabel') ||
      fullText.includes('data') ||
      fullText.includes('ciri-ciri') ||
      fullText.includes('sifat') ||
      subIndex < currentDraft.qNum // Number jumped back (e.g. at Q5, sees "1)")
    ) {
      return true;
    }
  }

  return false;
}

/**
 * Heuristic Recovery Engine (Auto-Healing):
 * Detects questions that were accidentally swallowed into options of previous questions
 * (e.g. Option D has 500 characters containing "19. ... A. ... B. ...").
 * Automatically splits and restores them so the question count is 100% complete and intact!
 */
function healSwallowedQuestions(drafts: RawQuestionDraft[]): { healedDrafts: RawQuestionDraft[]; recoveredCount: number } {
  const healed: RawQuestionDraft[] = [];
  let recoveredCount = 0;

  for (let d = 0; d < drafts.length; d++) {
    const current = drafts[d];

    // Check if the last option of this draft swallowed a subsequent question
    if (current.options.length > 0) {
      const lastOpt = current.options[current.options.length - 1];
      const optText = lastOpt.text;

      // Look for embedded question marker inside option text, e.g. "\n19. " or "\nSoal 19. "
      const embeddedQRegex = /(?:\n|\r|\s{3,})(?:soal\s+)?(?:no\.?\s*)?(\d+)[\.\)\:\-\s]\s*([^\n]+)/i;
      const embMatch = optText.match(embeddedQRegex);

      if (embMatch && embMatch.index !== undefined) {
        const swallowedNum = parseInt(embMatch[1], 10);
        const splitIndex = embMatch.index;

        // Clean current option text to only contain text before the swallowed question
        const cleanOptText = optText.substring(0, splitIndex).trim();
        const swallowedContent = optText.substring(splitIndex).trim();

        lastOpt.text = cleanOptText;

        // Parse swallowedContent into a new RawQuestionDraft
        const lines = swallowedContent.split('\n').map(l => l.trim()).filter(Boolean);
        const newDraft: RawQuestionDraft = {
          qNum: swallowedNum,
          textParts: [],
          images: [],
          options: []
        };

        let insideSwallowedOpt = false;
        for (const line of lines) {
          const qStart = matchQuestionStart(line);
          const optStart = matchOptionStart(line);
          const horizOpts = splitHorizontalOptions(line);

          if (qStart && newDraft.textParts.length === 0) {
            newDraft.textParts.push(qStart.remainingText || line);
          } else if (horizOpts && horizOpts.length >= 2) {
            insideSwallowedOpt = true;
            for (const ho of horizOpts) {
              newDraft.options.push(ho);
            }
          } else if (optStart) {
            insideSwallowedOpt = true;
            newDraft.options.push({
              letter: optStart.letter,
              text: optStart.optText,
              isCorrect: optStart.isCorrect
            });
          } else {
            if (insideSwallowedOpt && newDraft.options.length > 0) {
              newDraft.options[newDraft.options.length - 1].text += ` ${line}`;
            } else {
              newDraft.textParts.push(line);
            }
          }
        }

        healed.push(current);
        if (newDraft.textParts.length > 0 || newDraft.options.length > 0) {
          healed.push(newDraft);
          recoveredCount++;
        }
        continue;
      }
    }

    healed.push(current);
  }

  return { healedDrafts: healed, recoveredCount };
}

/**
 * Intelligent Parser for Microsoft Word (.docx) documents.
 * Features:
 * 1. OMML & Word Equation to LaTeX Conversion (fractions, square roots, exponents, superscripts, subscripts, Greek math)
 * 2. Automatic Word List (<ol><li>) and Table parsing support
 * 3. Stimulus & sub-item protection to prevent false question splitting
 * 4. Heuristic Auto-Healing to recover any swallowed questions and guarantee exact question count
 * 5. Automatic extraction of inline images and diagram attachments with WebP compression
 * 6. Bottom "KUNCI JAWABAN" matching for Single Choice (MC) and Multiple Response (MR)
 */
export async function parseDocxExamFile(
  fileBuffer: ArrayBuffer,
  targetSubjectId: string,
  defaultScore = 10
): Promise<WordImportResult> {
  const warnings: string[] = [];
  let mathFormulaCount = 0;

  // Step 1: Pre-process DOCX with JSZip to convert OMML Word Equations (<m:oMath>) to LaTeX ($...$)
  let processedBuffer = fileBuffer;
  try {
    const zip = await JSZip.loadAsync(fileBuffer);
    const docXmlFile = zip.file('word/document.xml');
    if (docXmlFile) {
      const rawXml = await docXmlFile.async('string');
      const { xml: injectedXml, mathCount } = injectLatexIntoWordDocumentXml(rawXml);
      if (mathCount > 0) {
        mathFormulaCount += mathCount;
        zip.file('word/document.xml', injectedXml);
        const transformedBlob = await zip.generateAsync({ type: 'arraybuffer' });
        processedBuffer = transformedBlob;
      }
    }
  } catch (err: any) {
    console.warn('OMML pre-processing fallback:', err?.message || err);
    // Proceed with original buffer if zip extraction encounters non-standard packaging
  }

  // Step 2: Convert to HTML using Mammoth with image extraction
  let extractedImageCount = 0;
  const mammothOptions = {
    convertImage: mammoth.images.imgElement(async (image: any) => {
      try {
        const buffer = await image.read('base64');
        const contentType = image.contentType || 'image/png';
        const rawDataUrl = `data:${contentType};base64,${buffer}`;
        extractedImageCount++;
        const compressed = await compressBase64DataUrl(rawDataUrl, 1000, 0.82);
        return { src: compressed };
      } catch (err: any) {
        warnings.push(`Peringatan ekstraksi gambar: ${err.message || 'Gagal'}`);
        return { src: '' };
      }
    })
  };

  const mammothResult = await mammoth.convertToHtml({ arrayBuffer: processedBuffer }, mammothOptions);
  const fullHtml = mammothResult.value;

  if (!fullHtml || !fullHtml.trim()) {
    throw new Error('Dokumen Word kosong atau tidak dapat diekstrak teksnya.');
  }

  // Step 3: Separate top questions section from bottom "KUNCI JAWABAN" section
  const keyHeaderRegex = /<h[1-6][^>]*>[\s\S]*?(?:kunci\s+jawaban|kunci\s+soal|kunci\s*:\s*|lembar\s+kunci)[\s\S]*?<\/h[1-6]>|<p[^>]*>[\s\S]*?<strong>[\s\S]*?(?:kunci\s+jawaban|kunci\s+soal|kunci\s*:\s*|lembar\s+kunci)[\s\S]*?<\/strong>[\s\S]*?<\/p>|(?:<p[^>]*>|<div[^>]*>)\s*(?:kunci\s+jawaban|kunci\s+soal|kunci\s*:\s*|lembar\s+kunci)[\s\S]*?(?:<\/p>|<\/div>)/i;

  let soalHtml = fullHtml;
  let kunciHtml = '';
  const keyMatch = fullHtml.match(keyHeaderRegex);

  if (!keyMatch) {
    const lower = fullHtml.toLowerCase();
    const idx = lower.lastIndexOf('kunci jawaban');
    if (idx !== -1) {
      soalHtml = fullHtml.substring(0, idx);
      kunciHtml = fullHtml.substring(idx);
    }
  } else if (keyMatch.index !== undefined) {
    soalHtml = fullHtml.substring(0, keyMatch.index);
    kunciHtml = fullHtml.substring(keyMatch.index);
  }

  // Parse answer keys from bottom section
  const parser = new DOMParser();
  const kunciDoc = parser.parseFromString(kunciHtml, 'text/html');
  const kunciText = kunciDoc.body.textContent || '';
  const answerKeyMap = parseAnswerKeysSection(kunciText, kunciHtml);

  // Step 4: Parse elements and normalize lists & tables
  const doc = parser.parseFromString(soalHtml, 'text/html');

  // Flatten nested <ol><li> structures so automatic Word numbering is not lost
  const flattenedNodes: { rawText: string; imgUrls: string[]; isLi?: boolean; liIndex?: number }[] = [];

  function traverseNode(node: Node) {
    if (node.nodeType !== 1) return;
    const el = node as HTMLElement;
    const tagName = el.tagName.toLowerCase();

    // Check images in this element
    const imgEls = Array.from(el.querySelectorAll('img'));
    const imgUrls = imgEls.map(img => img.getAttribute('src') || '').filter(Boolean);

    if (tagName === 'ol') {
      // Ordered list from Word automatic numbering
      const lis = Array.from(el.children).filter(c => c.tagName.toLowerCase() === 'li');
      let counter = 1;
      for (const li of lis) {
        const liImgEls = Array.from(li.querySelectorAll('img'));
        const liImgUrls = liImgEls.map(img => img.getAttribute('src') || '').filter(Boolean);
        const text = normalizeWordText(li.textContent || '');
        if (text || liImgUrls.length > 0) {
          flattenedNodes.push({
            rawText: text,
            imgUrls: liImgUrls,
            isLi: true,
            liIndex: counter++
          });
        }
      }
      return;
    }

    if (tagName === 'table') {
      // Check if table is a question table (grid format) or an in-question data table
      const rows = Array.from(el.querySelectorAll('tr'));
      let isQuestionTable = false;

      // If rows have numbers in column 0 like 1, 2, 3...
      if (rows.length >= 2) {
        const firstColFirstRow = rows[0].querySelector('td, th')?.textContent?.trim() || '';
        const firstColSecondRow = rows[1].querySelector('td, th')?.textContent?.trim() || '';
        if (/^\d+$/.test(firstColFirstRow) || /^\d+$/.test(firstColSecondRow)) {
          isQuestionTable = true;
        }
      }

      if (isQuestionTable) {
        for (const row of rows) {
          const cells = Array.from(row.querySelectorAll('td, th')).map(c => normalizeWordText(c.textContent || ''));
          const rImgEls = Array.from(row.querySelectorAll('img'));
          const rImgUrls = rImgEls.map(img => img.getAttribute('src') || '').filter(Boolean);
          if (cells.length >= 2) {
            flattenedNodes.push({
              rawText: cells.join(' | '),
              imgUrls: rImgUrls
            });
          }
        }
        return;
      }

      // If it's a data table inside a question, preserve it as formatted text
      const tableText = el.innerText || el.textContent || '';
      flattenedNodes.push({
        rawText: normalizeWordText(tableText),
        imgUrls
      });
      return;
    }

    if (['p', 'h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'div'].includes(tagName)) {
      const text = normalizeWordText(el.textContent || '');
      if (text || imgUrls.length > 0) {
        flattenedNodes.push({
          rawText: text,
          imgUrls
        });
      }
      return;
    }

    // Default: traverse children
    for (let i = 0; i < el.childNodes.length; i++) {
      traverseNode(el.childNodes[i]);
    }
  }

  for (let i = 0; i < doc.body.childNodes.length; i++) {
    traverseNode(doc.body.childNodes[i]);
  }

  // Step 5: State Machine to assemble RawQuestionDrafts
  const drafts: RawQuestionDraft[] = [];
  let currentDraft: RawQuestionDraft | null = null;
  let autoQuestionCounter = 1;

  for (const node of flattenedNodes) {
    const rawText = node.rawText;
    const imgUrls = node.imgUrls;

    // Check horizontal options first: e.g. "A. Merah   B. Kuning   C. Hijau   D. Biru"
    const horizontalOptions = splitHorizontalOptions(rawText);

    // Check single option match: e.g. "A. Pilihan"
    const singleOptionMatch = matchOptionStart(rawText);

    // Check question start match
    let qStart = matchQuestionStart(rawText);

    // If node came from an <ol><li>, and doesn't explicitly start with a number
    if (!qStart && node.isLi && node.liIndex) {
      // If it doesn't look like an option A/B/C/D
      if (!singleOptionMatch && !horizontalOptions) {
        qStart = {
          qNum: node.liIndex,
          remainingText: rawText
        };
      }
    }

    // Check if this might be a sub-item statement (stimulus) rather than a new question
    if (qStart && isSubStimulusItem(rawText, currentDraft)) {
      qStart = null; // Treat as continuation of question stimulus
    }

    // A) If a new question starts
    if (qStart) {
      if (currentDraft) {
        drafts.push(currentDraft);
      }

      currentDraft = {
        qNum: qStart.qNum || autoQuestionCounter++,
        textParts: qStart.remainingText ? [qStart.remainingText] : [],
        images: [...imgUrls],
        options: []
      };
      autoQuestionCounter = Math.max(autoQuestionCounter, currentDraft.qNum + 1);
      continue;
    }

    // B) Inside a question draft
    if (currentDraft) {
      // 1. Horizontal options
      if (horizontalOptions && horizontalOptions.length >= 2) {
        for (const opt of horizontalOptions) {
          const { text: enhancedOptText, hasMath } = enhanceMathText(opt.text);
          if (hasMath) mathFormulaCount++;
          currentDraft.options.push({
            letter: opt.letter,
            text: enhancedOptText,
            isCorrect: opt.isCorrect
          });
        }
        continue;
      }

      // 2. Single line option
      if (singleOptionMatch) {
        const { text: enhancedOptText, hasMath } = enhanceMathText(singleOptionMatch.optText);
        if (hasMath) mathFormulaCount++;

        currentDraft.options.push({
          letter: singleOptionMatch.letter,
          text: enhancedOptText,
          isCorrect: singleOptionMatch.isCorrect,
          image: imgUrls.length > 0 ? imgUrls[0] : undefined
        });
        continue;
      }

      // 3. Additional images
      if (imgUrls.length > 0) {
        currentDraft.images.push(...imgUrls);
      }

      // 4. Text continuation
      if (rawText) {
        // If question already has >= 4 options, and this text is not an option:
        // DO NOT SWALLOW into Option D! Treat as potential new question or sub-block
        if (currentDraft.options.length >= 4 && !singleOptionMatch) {
          // If text has significant length or starts with a number, create a recovered draft
          drafts.push(currentDraft);
          const recoveredStart = matchQuestionStart(rawText);
          currentDraft = {
            qNum: recoveredStart ? recoveredStart.qNum : autoQuestionCounter++,
            textParts: [recoveredStart ? recoveredStart.remainingText : rawText],
            images: [...imgUrls],
            options: []
          };
          autoQuestionCounter = Math.max(autoQuestionCounter, currentDraft.qNum + 1);
          continue;
        }

        if (currentDraft.options.length > 0) {
          // Append to last option only if options have started and count < 4
          const lastOpt = currentDraft.options[currentDraft.options.length - 1];
          const { text: enhancedAddon, hasMath } = enhanceMathText(rawText);
          if (hasMath) mathFormulaCount++;
          lastOpt.text += ` ${enhancedAddon}`;
        } else {
          // Question text continuation
          const { text: enhancedQuestionPart, hasMath } = enhanceMathText(rawText);
          if (hasMath) mathFormulaCount++;
          currentDraft.textParts.push(enhancedQuestionPart);
        }
      }
    } else {
      // Text before question #1 (e.g. instruction or stimulus)
      if (rawText.length > 15 || imgUrls.length > 0) {
        const { text: enhancedInit, hasMath } = enhanceMathText(rawText);
        if (hasMath) mathFormulaCount++;
        currentDraft = {
          qNum: autoQuestionCounter++,
          textParts: enhancedInit ? [enhancedInit] : [],
          images: [...imgUrls],
          options: []
        };
      }
    }
  }

  if (currentDraft) {
    drafts.push(currentDraft);
  }

  // Step 6: Run Heuristic Healing Engine to detect & split any swallowed questions
  const { healedDrafts, recoveredCount } = healSwallowedQuestions(drafts);
  if (recoveredCount > 0) {
    warnings.push(`Sistem berhasil mendeteksi dan memulihkan ${recoveredCount} butir soal yang sebelumnya sempat tergabung.`);
  }

  // Step 7: Build standardized Question objects
  const finalQuestions: Question[] = [];
  let mcCount = 0;
  let mrCount = 0;
  let withImgCount = 0;

  for (let i = 0; i < healedDrafts.length; i++) {
    const draft = healedDrafts[i];
    const qNumber = draft.qNum || (i + 1);

    // Build question text
    let fullQuestionText = draft.textParts.join('\n\n').trim();
    if (!fullQuestionText && draft.images.length > 0) {
      fullQuestionText = `Perhatikan gambar di bawah ini untuk menjawab soal no. ${qNumber}:`;
    }
    if (!fullQuestionText) {
      fullQuestionText = `Soal No. ${qNumber}`;
    }

    // Process options
    let opts = draft.options.map(o => o.text);
    const optImages = draft.options.map(o => o.image || '');

    if (opts.length < 2) {
      warnings.push(`Soal No. ${qNumber} memiliki kurang dari 2 pilihan jawaban.`);
      if (opts.length === 0) {
        opts = ['Pilihan A', 'Pilihan B', 'Pilihan C', 'Pilihan D'];
      }
    }

    // Determine correct answers
    let correctIndices: number[] = [];
    let qType: 'MC' | 'MR' = 'MC';

    // 1. From bottom answer keys section
    const bottomKeys = answerKeyMap.get(qNumber);
    if (bottomKeys && bottomKeys.length > 0) {
      correctIndices = bottomKeys
        .map(k => letterToIndex(k))
        .filter(idx => idx < Math.max(4, opts.length));

      if (correctIndices.length >= 2) {
        qType = 'MR'; // Multiple Response / Jawaban Ganda
      } else {
        qType = 'MC'; // Single choice
      }
    } else {
      // 2. From inline asterisk markers (*A. atau **B.)
      const inlineCorrect = draft.options
        .map((opt, idx) => (opt.isCorrect ? idx : -1))
        .filter(idx => idx !== -1);

      if (inlineCorrect.length >= 2) {
        correctIndices = inlineCorrect;
        qType = 'MR';
      } else if (inlineCorrect.length === 1) {
        correctIndices = inlineCorrect;
        qType = 'MC';
      } else {
        // Fallback default: option A
        correctIndices = [0];
        qType = 'MC';
      }
    }

    if (correctIndices.length === 0) {
      correctIndices = [0];
    }

    if (qType === 'MR') mrCount++;
    else mcCount++;

    const mainImageUrl = draft.images.length > 0 ? draft.images[0] : undefined;
    if (mainImageUrl) withImgCount++;

    const isPassage =
      fullQuestionText.length > 300 ||
      fullQuestionText.toLowerCase().includes('wacana') ||
      fullQuestionText.toLowerCase().includes('bacalah');

    const questionObj: Question = {
      id: `q_word_${Date.now()}_${i}_${Math.random().toString(36).substring(2, 6)}`,
      questionText: fullQuestionText,
      imageUrl: mainImageUrl,
      options: opts,
      optionImages: optImages.some(img => !!img) ? optImages : undefined,
      correctAnswerIndex: correctIndices[0],
      correctAnswerIndices: correctIndices,
      type: qType,
      score: defaultScore,
      subjectId: targetSubjectId,
      isReadingPassage: isPassage ? true : undefined
    };

    finalQuestions.push(questionObj);
  }

  if (finalQuestions.length === 0) {
    throw new Error(
      'Tidak ada butir soal yang berhasil diekstrak dari dokumen Word. Pastikan format penomoran soal (1. , 2. ) dan pilihan (A. , B. ) jelas.'
    );
  }

  // Calculate detected sequence string: e.g. "1 - 20 (Lengkap)"
  const qNums = healedDrafts.map((d, i) => d.qNum || (i + 1));
  const minNum = Math.min(...qNums);
  const maxNum = Math.max(...qNums);
  const isComplete = finalQuestions.length === (maxNum - minNum + 1);
  const detectedSequence = `${minNum} - ${maxNum} (${isComplete ? 'Lengkap & Rapi' : `${finalQuestions.length} Terdeteksi`})`;

  return {
    questions: finalQuestions,
    totalParsed: finalQuestions.length,
    mcCount,
    mrCount,
    imageCount: withImgCount,
    mathFormulaCount,
    recoveredQuestionCount: recoveredCount,
    detectedSequence,
    warnings
  };
}
