import JSZip from 'jszip';
import mammoth from 'mammoth';
import { Question } from '../types';
import { compressBase64DataUrl } from './imageCompressor';
import { injectLatexIntoWordDocumentXml } from './ommlToLatex';

export interface WordImportResult {
  questions: Question[];
  totalParsed: number;
  mcCount: number; // Single choice count
  mrCount: number; // Multiple response count
  imageCount: number; // Questions with embedded images
  mathFormulaCount: number; // Questions containing mathematical formulas/fractions
  recoveredQuestionCount: number; // Questions auto-healed/separated from swallowed blocks
  detectedSequence: string; // e.g. "1 - 25 (Lengkap & Rapi)"
  warnings: string[];
}

/**
 * Helper to convert letter ('A' | 'B' | 'C' | 'D' | 'E') to 0-based index.
 */
function letterToIndex(letter: string): number {
  const code = letter.toUpperCase().charCodeAt(0);
  return Math.max(0, code - 65); // 'A' -> 0, 'B' -> 1, 'C' -> 2, 'D' -> 3, 'E' -> 4
}

/**
 * Clean non-breaking spaces and normalize invisible Word characters.
 */
function normalizeWordText(text: string): string {
  if (!text) return '';
  return text
    .replace(/[\u00A0\u2007\u202F]/g, ' ') // Non-breaking spaces
    .replace(/[\u200B-\u200D\uFEFF]/g, '') // Zero-width spaces
    .replace(/\r\n/g, '\n')
    .replace(/\r/g, '\n')
    .replace(/[\t]+/g, ' ')
    .trim();
}

/**
 * Normalizes plain mathematical notations into KaTeX-compatible LaTeX:
 * - Superscripts: x², cm³, 10⁻⁵ -> $x^2$, cm$^3$, $10^{-5}$
 * - Subscripts: H₂O -> $H_2O$
 * - Degree: 90° -> $90^\circ$
 * - Symbols: ±, ×, ÷, ≤, ≥, ≠, π, √
 */
export function enhanceMathText(rawText: string): { text: string; hasMath: boolean } {
  if (!rawText) return { text: '', hasMath: false };

  let text = rawText;
  let hasMath = false;

  // Check if text already has LaTeX ($...$ or $$...$$)
  if (text.includes('$') || text.includes('\\frac') || text.includes('\\sqrt')) {
    hasMath = true;
  }

  // Convert HTML <sup> and <sub> tags generated by Mammoth from Word into LaTeX
  if (text.includes('<sup>') || text.includes('<sub>')) {
    hasMath = true;
    text = text.replace(/<sup>(.*?)<\/sup>/gi, (_, sup) => `^{${sup}}`);
    text = text.replace(/<sub>(.*?)<\/sub>/gi, (_, sub) => `_{${sub}}`);
  }

  // Convert common Unicode superscripts
  const unicodeSupMap: Record<string, string> = {
    '⁰': '0', '¹': '1', '²': '2', '³': '3', '⁴': '4',
    '⁵': '5', '⁶': '6', '⁷': '7', '⁸': '8', '⁹': '9',
    '⁺': '+', '⁻': '-', 'ⁿ': 'n', 'ˣ': 'x'
  };
  const supRegex = /([a-zA-Z0-9\)])([⁰¹²³⁴⁵⁶⁷⁸⁹⁺⁻ⁿˣ]+)/g;
  if (supRegex.test(text)) {
    hasMath = true;
    text = text.replace(supRegex, (_, base, sups) => {
      const converted = sups.split('').map((c: string) => unicodeSupMap[c] || c).join('');
      return `${base}^{${converted}}`;
    });
  }

  // Convert common Unicode roots: √x or √(x) or √25
  const rootRegex = /√([a-zA-Z0-9]+|\([^\)]+\))/g;
  if (rootRegex.test(text)) {
    hasMath = true;
    text = text.replace(rootRegex, (_, content) => {
      const clean = content.startsWith('(') && content.endsWith(')') ? content.slice(1, -1) : content;
      return `$\\sqrt{${clean}}$`;
    });
  }

  // Convert standalone square root symbol √ without immediate arg
  if (text.includes('√')) {
    hasMath = true;
    text = text.replace(/√\s*([0-9a-zA-Z]+)/g, '$\\sqrt{$1}$');
  }

  // Convert degree symbol attached to numbers: e.g. 45° or 180°
  text = text.replace(/(\d+)\s*°/g, '$1^\\circ');

  // Convert isolated common math symbols if inside algebraic context
  if (text.includes('±') || text.includes('≠') || text.includes('≤') || text.includes('≥') || text.includes('≈')) {
    hasMath = true;
  }

  return { text, hasMath };
}

/**
 * Checks if a string represents an exam header, instruction, or metadata block (Kop Surat / Petunjuk Umum).
 */
function isInstructionOrHeaderKeyword(text: string): boolean {
  const norm = normalizeWordText(text).toLowerCase();
  return (
    norm.includes('petunjuk umum') ||
    norm.includes('petunjuk khusus') ||
    norm.includes('petunjuk pengerjaan') ||
    norm.includes('petunjuk pengisian') ||
    norm.includes('tata tertib') ||
    norm.includes('lembar jawaban') ||
    norm.includes('mata pelajaran') ||
    norm.includes('penilaian akhir semester') ||
    norm.includes('asesmen sumatif') ||
    norm.includes('ujian akhir sekolah') ||
    norm.includes('berdoalah sebelum') ||
    norm.includes('periksa dan bacalah') ||
    norm.includes('alokasi waktu') ||
    norm.startsWith('waktu :') ||
    norm.startsWith('waktu:') ||
    norm.startsWith('kelas :') ||
    norm.startsWith('kelas:') ||
    norm.startsWith('hari/tanggal') ||
    norm.startsWith('tahun pelajaran') ||
    norm.startsWith('tahun ajaran')
  );
}

/**
 * Checks if a string represents the start of the Answer Keys section at the bottom.
 */
function isAnswerKeyHeader(text: string): boolean {
  const norm = normalizeWordText(text).toLowerCase();
  return (
    norm.startsWith('kunci jawaban') ||
    norm.startsWith('kunci soal') ||
    norm.startsWith('lembar kunci') ||
    norm.startsWith('kunci pilihan ganda') ||
    norm.startsWith('kunci :') ||
    norm === 'kunci' ||
    norm === 'kunci jawaban' ||
    norm.startsWith('answer key') ||
    norm.includes('kunci dan pembahasan') ||
    norm.includes('kunci jawaban:')
  );
}

/**
 * Parse bottom "Kunci Jawaban" section into a mapping of question number -> correct letter array.
 */
function parseAnswerKeysSection(text: string, html: string): Map<number, string[]> {
  const keyMap = new Map<number, string[]>();

  // 1. Try DOM table extraction first (if answer keys are in a table)
  try {
    const parser = new DOMParser();
    const doc = parser.parseFromString(html, 'text/html');
    const tables = doc.querySelectorAll('table');
    for (const table of tables) {
      const rows = table.querySelectorAll('tr');
      for (const row of rows) {
        const cells = Array.from(row.querySelectorAll('td, th')).map(c => normalizeWordText(c.textContent || ''));
        if (cells.length >= 2) {
          // Case A: 2 columns [No, Kunci]
          const qNum = parseInt(cells[0].replace(/[^\d]/g, ''), 10);
          if (!isNaN(qNum) && qNum > 0) {
            const letters = cells[1].toUpperCase().match(/[A-E]/g);
            if (letters && letters.length > 0) {
              keyMap.set(qNum, Array.from(new Set(letters)));
            }
          }
          // Case B: Multi-pair columns in grid [No, Kunci, No, Kunci, ...]
          for (let c = 0; c < cells.length - 1; c += 2) {
            const pairNum = parseInt(cells[c].replace(/[^\d]/g, ''), 10);
            if (!isNaN(pairNum) && pairNum > 0) {
              const pairLetters = cells[c + 1].toUpperCase().match(/[A-E]/g);
              if (pairLetters && pairLetters.length > 0) {
                keyMap.set(pairNum, Array.from(new Set(pairLetters)));
              }
            }
          }
        }
      }
    }
  } catch {
    // ignore
  }

  if (keyMap.size > 0) return keyMap;

  // 2. Parse plain text line by line or pattern matches
  // Matches patterns like: "1. A", "1) B, C", "1: A & D", "No. 1: B", "1 = A", "1.A 2.B 3.C"
  const itemRegex = /(?:(?:no\.?\s*)?(\d+)[\.\)\:\=\s\-]+([A-Ea-e\s\,\&\/\+dan]+))/gi;
  let match: RegExpExecArray | null;

  while ((match = itemRegex.exec(text)) !== null) {
    const qNum = parseInt(match[1], 10);
    const rawVal = match[2];
    if (!isNaN(qNum) && qNum > 0 && rawVal) {
      const letters = rawVal.toUpperCase().match(/[A-E]/g);
      if (letters && letters.length > 0) {
        keyMap.set(qNum, Array.from(new Set(letters)));
      }
    }
  }

  // 3. Fallback line by line
  if (keyMap.size === 0) {
    const lines = text.split('\n');
    for (const line of lines) {
      const trimmed = normalizeWordText(line);
      if (!trimmed) continue;
      const lineMatch = trimmed.match(/^(?:no\.?\s*)?(\d+)[\.\)\:\=\s\-]+(.*)$/i);
      if (lineMatch) {
        const qNum = parseInt(lineMatch[1], 10);
        const letters = lineMatch[2].toUpperCase().match(/[A-E]/g);
        if (!isNaN(qNum) && letters && letters.length > 0) {
          keyMap.set(qNum, Array.from(new Set(letters)));
        }
      }
    }
  }

  return keyMap;
}

/**
 * Split single text line containing multiple horizontal options into separate options.
 * e.g. "A. Merah   B. Kuning   C. Hijau   D. Biru"
 */
function splitHorizontalOptions(text: string): { letter: string; text: string; isCorrect: boolean }[] | null {
  const markerRegex = /(?:^|[\s\t]{2,}|\n)([\*]{1,2})?\s*\(?([A-Ea-e])\)?[.\-\s]\s*/g;
  const matches: { index: number; length: number; letter: string; asterisks: string }[] = [];
  let m: RegExpExecArray | null;

  while ((m = markerRegex.exec(text)) !== null) {
    matches.push({
      index: m.index,
      length: m[0].length,
      letter: m[2].toUpperCase(),
      asterisks: m[1] || ''
    });
  }

  if (matches.length >= 2) {
    const results: { letter: string; text: string; isCorrect: boolean }[] = [];
    for (let i = 0; i < matches.length; i++) {
      const start = matches[i].index + matches[i].length;
      const end = i + 1 < matches.length ? matches[i + 1].index : text.length;
      const optContent = text.substring(start, end).trim();
      results.push({
        letter: matches[i].letter,
        text: optContent,
        isCorrect: matches[i].asterisks.length > 0
      });
    }
    return results;
  }

  return null;
}

interface RawOption {
  letter: string;
  text: string;
  isCorrect: boolean;
  image?: string;
}

interface RawQuestionDraft {
  qNum: number;
  textParts: string[];
  images: string[];
  options: RawOption[];
}

/**
 * Checks if a string looks like an option starting marker:
 * e.g. "A. ", "B. ", "a) ", "*C. ", "**D. "
 */
function matchOptionStart(text: string): { letter: string; optText: string; isCorrect: boolean } | null {
  const normalized = normalizeWordText(text);
  if (!normalized) return null;

  // Match: "*A. Pilihan" or "A. Pilihan" or "A) Pilihan" or "(A) Pilihan" or "a. Pilihan"
  const m = normalized.match(/^(\*{1,2})?\s*\(?([A-Ea-e])\)?[.\-\s]\s*(.*)$/);
  if (m) {
    const asterisks = m[1] || '';
    const letter = m[2].toUpperCase();
    const optText = m[3] ? m[3].trim() : '';

    // Guard against common false positives like "A. Yani" or "B. J. Habibie"
    if (optText.match(/^[A-Z]\.\s+[A-Za-z]+/)) {
      return null;
    }

    return {
      letter,
      optText,
      isCorrect: asterisks.length > 0
    };
  }

  return null;
}

/**
 * Strict Question Start Matcher:
 * Prevents ordinary sentences starting with numbers (e.g. "10 kg", "2 buah", "2024 adalah")
 * from ever being falsely matched as new questions!
 */
function matchStrictQuestionStart(
  text: string,
  currentDraft: RawQuestionDraft | null,
  hasFirstQuestionStarted: boolean
): { qNum: number; remainingText: string } | null {
  const norm = normalizeWordText(text);
  if (!norm) return null;

  // 1. Explicit prefix: 'Soal 1. ', 'No. 1. ', 'Nomor 1: '
  const prefixMatch = norm.match(/^(?:soal\s+|nomor\s+|no\.?\s*)(\d+)[\.\:\-\)]?\s*(.*)$/i);
  if (prefixMatch) {
    const num = parseInt(prefixMatch[1], 10);
    return { qNum: num, remainingText: prefixMatch[2] ? prefixMatch[2].trim() : '' };
  }

  // 2. Strict number with dot: '1. ', '2. ', '25. '
  // MUST have whitespace after dot so decimals like '1.5' or '3.14' are never matched!
  const dotMatch = norm.match(/^(\d+)\.\s+(.*)$/);
  if (dotMatch) {
    const num = parseInt(dotMatch[1], 10);

    // If Question 1 has not started yet and we see '1.', this is the real Question 1!
    if (!hasFirstQuestionStarted && num === 1) {
      return { qNum: 1, remainingText: dotMatch[2] ? dotMatch[2].trim() : '' };
    }

    // Check if this could be a sub-statement inside current question body (before options started)
    if (currentDraft && currentDraft.options.length === 0 && currentDraft.textParts.length > 0) {
      const bodyText = currentDraft.textParts.join(' ').toLowerCase();
      if (
        (bodyText.includes('perhatikan') ||
          bodyText.includes('berikut') ||
          bodyText.includes('pernyataan') ||
          bodyText.includes('ciri') ||
          bodyText.includes('sifat') ||
          bodyText.includes('data') ||
          bodyText.includes('tabel')) &&
        num <= currentDraft.qNum
      ) {
        return null; // Statement item inside question body, keep as question stimulus!
      }
    }

    return { qNum: num, remainingText: dotMatch[2] ? dotMatch[2].trim() : '' };
  }

  // 3. Parenthesis: '1) ', '(1) ', '[1] '
  const parenMatch = norm.match(/^(?:(\d+)\)|[\(\[](\d+)[\)\]])\s+(.*)$/);
  if (parenMatch) {
    const num = parseInt(parenMatch[1] || parenMatch[2], 10);
    // If inside question body before options, parentheses '1)' are almost always stimulus items!
    if (currentDraft && currentDraft.options.length === 0 && currentDraft.textParts.length > 0) {
      return null;
    }
    return { qNum: num, remainingText: parenMatch[3] ? parenMatch[3].trim() : '' };
  }

  return null;
}

/**
 * Splits document HTML into:
 * 1. soalHtml (Questions section)
 * 2. kunciHtml (Answer keys section at the bottom)
 * Uses both DOM search and keyword search to prevent answer keys from ever leaking into questions.
 */
function splitDocumentHtml(fullHtml: string): { soalHtml: string; kunciHtml: string } {
  try {
    const parser = new DOMParser();
    const doc = parser.parseFromString(fullHtml, 'text/html');

    // Search for answer key heading elements in DOM
    const allElements = Array.from(doc.body.querySelectorAll('h1, h2, h3, h4, h5, h6, p, div, table, strong, b'));
    let splitIndex = -1;

    for (let i = allElements.length - 1; i >= 0; i--) {
      const el = allElements[i];
      const text = normalizeWordText(el.textContent || '');
      if (isAnswerKeyHeader(text)) {
        // Find this text in fullHtml
        const rawText = el.textContent?.trim() || '';
        if (rawText.length > 0) {
          const idx = fullHtml.lastIndexOf(rawText);
          if (idx !== -1 && (splitIndex === -1 || idx < splitIndex)) {
            splitIndex = idx;
          }
        }
      }
    }

    if (splitIndex !== -1) {
      return {
        soalHtml: fullHtml.substring(0, splitIndex),
        kunciHtml: fullHtml.substring(splitIndex)
      };
    }
  } catch {
    // fallback
  }

  // Fallback string-based search from the bottom
  const lower = fullHtml.toLowerCase();
  const searchTerms = [
    'kunci jawaban',
    'kunci soal',
    'lembar kunci',
    'kunci pilihan ganda',
    'kunci dan pembahasan',
    'answer key',
    'kunci :'
  ];

  for (const term of searchTerms) {
    const idx = lower.lastIndexOf(term);
    if (idx !== -1 && idx > fullHtml.length * 0.3) {
      // Find opening tag before this index if possible
      const tagOpen = fullHtml.lastIndexOf('<', idx);
      const cutPoint = tagOpen !== -1 ? tagOpen : idx;
      return {
        soalHtml: fullHtml.substring(0, cutPoint),
        kunciHtml: fullHtml.substring(cutPoint)
      };
    }
  }

  return { soalHtml: fullHtml, kunciHtml: '' };
}

/**
 * Intelligent Parser for Microsoft Word (.docx) documents.
 * Features:
 * 1. OMML & Word Equation to LaTeX Conversion (fractions, roots, exponents, Greek math)
 * 2. Header & "Petunjuk Umum" Discarding (no fake questions created from instructions!)
 * 3. Strict Question Start Detection (never cuts questions at numbers inside sentences like '10 kg')
 * 4. Stimulus & sub-item protection to prevent false question splitting
 * 5. Automatic extraction of inline images and diagram attachments with WebP compression
 * 6. Clean Answer Key extraction from bottom section without question leakage
 * 7. Enforces that only valid items with choices (A, B, C, D) become questions
 */
export async function parseDocxExamFile(
  fileBuffer: ArrayBuffer,
  targetSubjectId: string,
  defaultScore = 10
): Promise<WordImportResult> {
  const warnings: string[] = [];
  let mathFormulaCount = 0;

  // Step 1: Pre-process DOCX with JSZip to convert OMML Word Equations (<m:oMath>) to LaTeX ($...$)
  let processedBuffer = fileBuffer;
  try {
    const zip = await JSZip.loadAsync(fileBuffer);
    const docXmlFile = zip.file('word/document.xml');
    if (docXmlFile) {
      const rawXml = await docXmlFile.async('string');
      const { xml: injectedXml, mathCount } = injectLatexIntoWordDocumentXml(rawXml);
      if (mathCount > 0) {
        mathFormulaCount += mathCount;
        zip.file('word/document.xml', injectedXml);
        const transformedBlob = await zip.generateAsync({ type: 'arraybuffer' });
        processedBuffer = transformedBlob;
      }
    }
  } catch (err: any) {
    console.warn('OMML pre-processing fallback:', err?.message || err);
  }

  // Step 2: Convert to HTML using Mammoth with image extraction
  let extractedImageCount = 0;
  const mammothOptions = {
    convertImage: mammoth.images.imgElement(async (image: any) => {
      try {
        const buffer = await image.read('base64');
        const contentType = image.contentType || 'image/png';
        const rawDataUrl = `data:${contentType};base64,${buffer}`;
        extractedImageCount++;
        const compressed = await compressBase64DataUrl(rawDataUrl, 1000, 0.82);
        return { src: compressed };
      } catch (err: any) {
        warnings.push(`Peringatan ekstraksi gambar: ${err.message || 'Gagal'}`);
        return { src: '' };
      }
    })
  };

  const mammothResult = await mammoth.convertToHtml({ arrayBuffer: processedBuffer }, mammothOptions);
  const fullHtml = mammothResult.value;

  if (!fullHtml || !fullHtml.trim()) {
    throw new Error('Dokumen Word kosong atau tidak dapat diekstrak teksnya.');
  }

  // Step 3: Separate top questions section from bottom "KUNCI JAWABAN" section
  const { soalHtml, kunciHtml } = splitDocumentHtml(fullHtml);

  // Parse answer keys from bottom section
  const parser = new DOMParser();
  const kunciDoc = parser.parseFromString(kunciHtml, 'text/html');
  const kunciText = kunciDoc.body.textContent || '';
  const answerKeyMap = parseAnswerKeysSection(kunciText, kunciHtml);

  // Step 4: Parse elements and normalize lists & tables
  const doc = parser.parseFromString(soalHtml, 'text/html');

  // Flatten nested structures so automatic Word numbering is not lost
  const flattenedNodes: { rawText: string; imgUrls: string[]; isLi?: boolean; liIndex?: number }[] = [];

  function traverseNode(node: Node) {
    if (node.nodeType !== 1) return;
    const el = node as HTMLElement;
    const tagName = el.tagName.toLowerCase();

    // Check images in this element
    const imgEls = Array.from(el.querySelectorAll('img'));
    const imgUrls = imgEls.map(img => img.getAttribute('src') || '').filter(Boolean);

    if (tagName === 'ol') {
      // Ordered list from Word automatic numbering
      const lis = Array.from(el.children).filter(c => c.tagName.toLowerCase() === 'li');
      let counter = 1;
      for (const li of lis) {
        const liImgEls = Array.from(li.querySelectorAll('img'));
        const liImgUrls = liImgEls.map(img => img.getAttribute('src') || '').filter(Boolean);
        const text = normalizeWordText(li.textContent || '');
        if (text || liImgUrls.length > 0) {
          flattenedNodes.push({
            rawText: text,
            imgUrls: liImgUrls,
            isLi: true,
            liIndex: counter++
          });
        }
      }
      return;
    }

    if (tagName === 'table') {
      const rows = Array.from(el.querySelectorAll('tr'));
      let isQuestionTable = false;

      // If rows have numbers in column 0 like 1, 2, 3...
      if (rows.length >= 2) {
        const firstColFirstRow = rows[0].querySelector('td, th')?.textContent?.trim() || '';
        const firstColSecondRow = rows[1].querySelector('td, th')?.textContent?.trim() || '';
        if (/^\d+$/.test(firstColFirstRow) || /^\d+$/.test(firstColSecondRow)) {
          isQuestionTable = true;
        }
      }

      if (isQuestionTable) {
        for (const row of rows) {
          const cells = Array.from(row.querySelectorAll('td, th')).map(c => normalizeWordText(c.textContent || ''));
          const rImgEls = Array.from(row.querySelectorAll('img'));
          const rImgUrls = rImgEls.map(img => img.getAttribute('src') || '').filter(Boolean);
          if (cells.length >= 2) {
            flattenedNodes.push({
              rawText: cells.join(' | '),
              imgUrls: rImgUrls
            });
          }
        }
        return;
      }

      // If it's a data table inside a question, preserve it as formatted text
      const tableText = el.innerText || el.textContent || '';
      flattenedNodes.push({
        rawText: normalizeWordText(tableText),
        imgUrls
      });
      return;
    }

    if (['p', 'h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'div'].includes(tagName)) {
      const text = normalizeWordText(el.textContent || '');
      if (text || imgUrls.length > 0) {
        flattenedNodes.push({
          rawText: text,
          imgUrls
        });
      }
      return;
    }

    // Default: traverse children
    for (let i = 0; i < el.childNodes.length; i++) {
      traverseNode(el.childNodes[i]);
    }
  }

  for (let i = 0; i < doc.body.childNodes.length; i++) {
    traverseNode(doc.body.childNodes[i]);
  }

  // Step 5: State Machine to assemble RawQuestionDrafts
  const drafts: RawQuestionDraft[] = [];
  let currentDraft: RawQuestionDraft | null = null;
  let hasFirstQuestionStarted = false;
  let inInstructionBlock = false;

  for (const node of flattenedNodes) {
    const rawText = node.rawText;
    const imgUrls = node.imgUrls;

    // A) If before Question 1: check for exam header / instructions (Petunjuk Umum)
    if (!hasFirstQuestionStarted) {
      if (isInstructionOrHeaderKeyword(rawText)) {
        inInstructionBlock = true;
        continue;
      }
    }

    // B) Check horizontal options: e.g. "A. Merah   B. Kuning   C. Hijau   D. Biru"
    const horizontalOptions = splitHorizontalOptions(rawText);

    // C) Check single option match: e.g. "A. Pilihan"
    const singleOptionMatch = matchOptionStart(rawText);

    // D) Check strict question start match
    let qStart = matchStrictQuestionStart(rawText, currentDraft, hasFirstQuestionStarted);

    // If node came from an <ol><li> with Word automatic numbering
    if (!qStart && node.isLi && node.liIndex) {
      if (!singleOptionMatch && !horizontalOptions) {
        // If question 1 hasn't started yet and item index is 1, start Q1
        if (!hasFirstQuestionStarted && node.liIndex === 1 && !inInstructionBlock) {
          qStart = { qNum: 1, remainingText: rawText };
        } else if (hasFirstQuestionStarted) {
          // If options have already started on current question, new li is the next question
          if (currentDraft && currentDraft.options.length >= 2) {
            qStart = { qNum: node.liIndex, remainingText: rawText };
          }
        }
      }
    }

    // If strict question start matched
    if (qStart) {
      if (!hasFirstQuestionStarted) {
        if (qStart.qNum === 1) {
          // Real Question 1 has officially arrived!
          hasFirstQuestionStarted = true;
          inInstructionBlock = false;
          // Clear any preliminary drafts from header/instructions
          drafts.length = 0;
          currentDraft = {
            qNum: 1,
            textParts: qStart.remainingText ? [qStart.remainingText] : [],
            images: [...imgUrls],
            options: []
          };
          continue;
        } else if (inInstructionBlock) {
          // Instruction bullet point before Question 1 (e.g. '1. Berdoalah...', '2. Periksa...')
          continue;
        }
      }

      if (currentDraft) {
        drafts.push(currentDraft);
      }

      currentDraft = {
        qNum: qStart.qNum,
        textParts: qStart.remainingText ? [qStart.remainingText] : [],
        images: [...imgUrls],
        options: []
      };
      continue;
    }

    // If still in instruction block before Question 1, ignore
    if (inInstructionBlock && !hasFirstQuestionStarted) {
      continue;
    }

    // E) Inside a Question Draft
    if (currentDraft) {
      // 1. Horizontal options
      if (horizontalOptions && horizontalOptions.length >= 2) {
        for (const opt of horizontalOptions) {
          const { text: enhancedOptText, hasMath } = enhanceMathText(opt.text);
          if (hasMath) mathFormulaCount++;
          currentDraft.options.push({
            letter: opt.letter,
            text: enhancedOptText,
            isCorrect: opt.isCorrect
          });
        }
        continue;
      }

      // 2. Single line option
      if (singleOptionMatch) {
        const { text: enhancedOptText, hasMath } = enhanceMathText(singleOptionMatch.optText);
        if (hasMath) mathFormulaCount++;

        currentDraft.options.push({
          letter: singleOptionMatch.letter,
          text: enhancedOptText,
          isCorrect: singleOptionMatch.isCorrect,
          image: imgUrls.length > 0 ? imgUrls[0] : undefined
        });
        continue;
      }

      // 3. Additional images
      if (imgUrls.length > 0) {
        currentDraft.images.push(...imgUrls);
      }

      // 4. Text continuation
      if (rawText) {
        if (currentDraft.options.length > 0) {
          // Append continuation to the last option
          const lastOpt = currentDraft.options[currentDraft.options.length - 1];
          const { text: enhancedAddon, hasMath } = enhanceMathText(rawText);
          if (hasMath) mathFormulaCount++;
          lastOpt.text += ` ${enhancedAddon}`;
        } else {
          // Question text continuation (stimulus, story, data)
          const { text: enhancedQuestionPart, hasMath } = enhanceMathText(rawText);
          if (hasMath) mathFormulaCount++;
          currentDraft.textParts.push(enhancedQuestionPart);
        }
      }
    }
  }

  if (currentDraft) {
    drafts.push(currentDraft);
  }

  // Step 6: Filter out non-questions (Must have at least 2 choices: A and B)
  // This completely eliminates fake questions from instructions, headers, or blank lines!
  const validDrafts = drafts.filter(d => d.options.length >= 2);

  if (validDrafts.length === 0) {
    throw new Error(
      'Tidak ada butir soal pilihan ganda yang berhasil diekstrak. Pastikan format nomor soal (1. , 2. ) dan pilihan (A. , B. ) jelas.'
    );
  }

  // Step 7: Build standardized Question objects with 1-based sequential re-indexing
  const finalQuestions: Question[] = [];
  let mcCount = 0;
  let mrCount = 0;
  let withImgCount = 0;

  for (let i = 0; i < validDrafts.length; i++) {
    const draft = validDrafts[i];
    const sequentialNum = i + 1;
    const originalNum = draft.qNum || sequentialNum;

    // Build question text
    let fullQuestionText = draft.textParts.join('\n\n').trim();
    if (!fullQuestionText && draft.images.length > 0) {
      fullQuestionText = `Perhatikan gambar di bawah ini untuk menjawab soal no. ${sequentialNum}:`;
    }
    if (!fullQuestionText) {
      fullQuestionText = `Soal No. ${sequentialNum}`;
    }

    // Process options
    const opts = draft.options.map(o => o.text);
    const optImages = draft.options.map(o => o.image || '');

    // Determine correct answers: check originalNum first, then sequentialNum
    let correctIndices: number[] = [];
    let qType: 'MC' | 'MR' = 'MC';

    const bottomKeys = answerKeyMap.get(originalNum) || answerKeyMap.get(sequentialNum);
    if (bottomKeys && bottomKeys.length > 0) {
      correctIndices = bottomKeys
        .map(k => letterToIndex(k))
        .filter(idx => idx < opts.length);

      if (correctIndices.length >= 2) {
        qType = 'MR';
      } else {
        qType = 'MC';
      }
    } else {
      // Inline asterisk markers (*A. atau **B.)
      const inlineCorrect = draft.options
        .map((opt, idx) => (opt.isCorrect ? idx : -1))
        .filter(idx => idx !== -1);

      if (inlineCorrect.length >= 2) {
        correctIndices = inlineCorrect;
        qType = 'MR';
      } else if (inlineCorrect.length === 1) {
        correctIndices = inlineCorrect;
        qType = 'MC';
      } else {
        correctIndices = [0];
        qType = 'MC';
      }
    }

    if (correctIndices.length === 0) {
      correctIndices = [0];
    }

    if (qType === 'MR') mrCount++;
    else mcCount++;

    const mainImageUrl = draft.images.length > 0 ? draft.images[0] : undefined;
    if (mainImageUrl) withImgCount++;

    const isPassage =
      fullQuestionText.length > 300 ||
      fullQuestionText.toLowerCase().includes('wacana') ||
      fullQuestionText.toLowerCase().includes('bacalah');

    const questionObj: Question = {
      id: `q_word_${Date.now()}_${i}_${Math.random().toString(36).substring(2, 6)}`,
      questionText: fullQuestionText,
      imageUrl: mainImageUrl,
      options: opts,
      optionImages: optImages.some(img => !!img) ? optImages : undefined,
      correctAnswerIndex: correctIndices[0],
      correctAnswerIndices: correctIndices,
      type: qType,
      score: defaultScore,
      subjectId: targetSubjectId,
      isReadingPassage: isPassage ? true : undefined
    };

    finalQuestions.push(questionObj);
  }

  const detectedSequence = `1 - ${finalQuestions.length} (Lengkap & Rapi)`;

  return {
    questions: finalQuestions,
    totalParsed: finalQuestions.length,
    mcCount,
    mrCount,
    imageCount: withImgCount,
    mathFormulaCount,
    recoveredQuestionCount: 0,
    detectedSequence,
    warnings
  };
}
